from enum import Enum

###### battery_config.h & bms_module.h  constants ######

HV_BATT_OC_THRESHOLD = 60.0 	#Should be set to 60.0A
HV_BATT_OV_THRESHOLD = 4.25  #Should be set to 4.25V
HV_BATT_UV_THRESHOLD = 2.50	#Should be set to 2.50V
HV_BATT_OT_THRESHOLD = 60.0 	#Should be set to 60.0C
HV_BATT_UT_THRESHOLD = 0.0   #Should be set to 0.0C


BMS_MODULE_NUM_STATE_OF_CHARGES = BMS_MODULE_NUM_VOLTAGES = NUM_CELLS_PER_MODULE = 5
NUM_BMS_MODULES	= 6 #Number of BMS modules to read from
NUM_BATT_CELLS = NUM_BMS_MODULES*NUM_CELLS_PER_MODULE #Number of series parallel groups in battery pack
BMS_MODULE_NUM_TEMPERATURES = BMS_MODULE_NUM_TEMPERATURE_SENSOR = NUM_TEMP_SENSORS_PER_MODULE = 3 
NUM_BATT_TEMP_SENSORS =	NUM_TEMP_SENSORS_PER_MODULE*NUM_BMS_MODULES #Number of temperature sensors in battery pack	


BATTERY_CELL_VOLTAGES_INITIAL_VALUE = -1000.0
BATTERY_CELL_VOLTAGES_FAKE_VALUE = 0.0
BATTERY_TEMPERATURES_INITIAL_VALUE = -1000.0
BATTERY_SOC_INITIAL_VALUE = -1000.0

MAX_ALLOWD_OVERCURRENT_TIME = 7000 # 7 seconds
MOTOR_OT_THRESHOLD = 180.0 # 180.0C
MOTOR_OT_WARNING_THRESHOLD =  100.0 # 100.0C 

HV_BATT_OV_DEBOUNCE_TIME  = 3000 # 3 seconds
HV_BATT_UV_DEBOUNCE_TIME =  3000 # 3 seconds

STATIC_FLOAT_QUEUE_NUM_VALUES = 20

###### end of battery_config.h & bms_module.h constants ######

